// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApRHNNeJyHdQ2OIRqAtWXIdeJB3tphBA',
    appId: '1:897647377174:web:dfe8977541c182b7922e37',
    messagingSenderId: '897647377174',
    projectId: 'tradehart-f5f44',
    authDomain: 'tradehart-f5f44.firebaseapp.com',
    storageBucket: 'tradehart-f5f44.appspot.com',
    measurementId: 'G-QMQKZPYC3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZrxiP-YdgMCDMcdG6UdyAGD29V1X6WXM',
    appId: '1:897647377174:android:07098accabcc5f73922e37',
    messagingSenderId: '897647377174',
    projectId: 'tradehart-f5f44',
    storageBucket: 'tradehart-f5f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaKpqFXcAFWwlXO5KECWZY69Jy-ECdL8U',
    appId: '1:897647377174:ios:0479ac818b46149c922e37',
    messagingSenderId: '897647377174',
    projectId: 'tradehart-f5f44',
    storageBucket: 'tradehart-f5f44.appspot.com',
    iosClientId: '897647377174-h906fdvk523a59nf5jd3002om51jovs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeHart',
  );
}
