// import 'package:trade_hart/model/service.dart';

// var services = [
//   Service(
//     name: "Service de nettoyage à domicile",
//     provider: "CleanService",
//     description: "Nettoyage professionnel de votre domicile",
//     price: 50.0,
//     rate: 4,
//     nbRate: 10,
//     imagePath: "images/services/image1.jpg",
//   ),
//   Service(
//     name: "Cours de fitness personnel",
//     provider: "FitInstructor",
//     description: "Séances de fitness personnalisées",
//     price: 30.0,
//     rate: 5,
//     nbRate: 8,
//     imagePath: "images/services/image2.jpg",
//   ),
//   Service(
//     name: "Services de jardinage",
//     provider: "GreenThumb",
//     description: "Entretien et aménagement de jardins",
//     price: 40.0,
//     rate: 4,
//     nbRate: 12,
//     imagePath: "images/services/image3.jpg",
//   ),
//   Service(
//     name: "Consultation en nutrition",
//     provider: "NutriHealth",
//     description: "Conseils nutritionnels personnalisés",
//     price: 25.0,
//     rate: 5,
//     nbRate: 15,
//     imagePath: "images/services/image4.jpg",
//   ),
//   Service(
//     name: "Dépannage informatique",
//     provider: "TechRescue",
//     description: "Assistance et réparation informatique",
//     price: 60.0,
//     rate: 4,
//     nbRate: 7,
//     imagePath: "images/services/image5.jpg",
//   ),
//   Service(
//     name: "Cours de photographie",
//     provider: "PhotoMaster",
//     description: "Apprenez les bases de la photographie",
//     price: 35.0,
//     rate: 5,
//     nbRate: 20,
//     imagePath: "images/services/image6.jpg",
//   ),
//   Service(
//     name: "Services de baby-sitting",
//     provider: "CaringHands",
//     description: "Garde d'enfants fiable et attentionnée",
//     price: 20.0,
//     rate: 4,
//     nbRate: 5,
//     imagePath: "images/services/image7.jpg",
//   ),
//   Service(
//     name: "Conception de site web",
//     provider: "WebCraft",
//     description: "Création professionnelle de sites web",
//     price: 80.0,
//     rate: 5,
//     nbRate: 18,
//     imagePath: "images/services/image8.jpg",
//   ),
//   Service(
//     name: "Cours de langue étrangère",
//     provider: "LingoLearn",
//     description: "Apprenez une nouvelle langue avec des cours interactifs",
//     price: 45.0,
//     rate: 4,
//     nbRate: 14,
//     imagePath: "images/services/image9.jpg",
//   ),
//   Service(
//     name: "Services de plomberie",
//     provider: "PlumbHero",
//     description: "Réparation et installation de plomberie",
//     price: 55.0,
//     rate: 5,
//     nbRate: 22,
//     imagePath: "images/services/image10.jpg",
//   ),
// ];
